[project]
name = "itksnap-dls"
version = "0.1.4"
authors = [
  { name="Paul Yushkevich", email="pyushkevich@gmail.com" },
]
description = "ITK-SNAP interactive deep learning segmentation server"
dependencies = [
    'fastapi[standard]',
    'nnInteractive',
    'huggingface_hub',
    'transformers',
    'ngrok',
    'torch<=2.8.0',
    'torchaudio<=2.8.0',
    "httpx>=0.28.1",
    "pydantic-settings>=2.15.0",
]
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Development Status :: 4 - Beta",
    "Topic :: Scientific/Engineering :: Medical Science Apps."
]

[project.urls]
Homepage = "https://github.com/pyushkevich/itksnap"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["itksnap_dls" ]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-mock>=3.15.1",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
markers = [
    "unit: isolated tests for individual functions/classes, no external dependencies",
    "integration: end-to-end tests through the FastAPI app",
]
